package usam.persistencia;
// Generated 08-21-2018 04:38:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private String codigoDepartamento;
     private String departamento;
     private Date fechaCreacion;

    public Departamentos() {
    }

	
    public Departamentos(String codigoDepartamento) {
        this.codigoDepartamento = codigoDepartamento;
    }
    public Departamentos(String codigoDepartamento, String departamento, Date fechaCreacion) {
       this.codigoDepartamento = codigoDepartamento;
       this.departamento = departamento;
       this.fechaCreacion = fechaCreacion;
    }
   
    public String getCodigoDepartamento() {
        return this.codigoDepartamento;
    }
    
    public void setCodigoDepartamento(String codigoDepartamento) {
        this.codigoDepartamento = codigoDepartamento;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


